set(BIN_OUTPUT_DIR "${CMAKE_BINARY_DIR}/../bin")
set(LIB_OUTPUT_DIR "${CMAKE_BINARY_DIR}/../lib")
set(LIB_DEBUG_PATH "${LIB_OUTPUT_DIR}/Debug/")
set(LIB_RELEASE_PATH "${LIB_OUTPUT_DIR}/Release/")
set(GLOBAL_ALL_TARGETS)

macro(ConfigureTarget TARGET_NAME)
set_target_properties(${TARGET_NAME} PROPERTIES
					LIBRARY_OUTPUT_DIRECTORY_DEBUG "${LIB_OUTPUT_DIR}/Debug/"
					ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${LIB_OUTPUT_DIR}/Debug/"
					RUNTIME_OUTPUT_DIRECTORY_DEBUG "${BIN_OUTPUT_DIR}/Debug/"
					LIBRARY_OUTPUT_DIRECTORY_RELEASE "${LIB_OUTPUT_DIR}/Release/"
					ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${LIB_OUTPUT_DIR}/Release/"
					RUNTIME_OUTPUT_DIRECTORY_RELEASE "${BIN_OUTPUT_DIR}/Release/"
					)
endmacro()

macro(TopAddTarget TARGET_NAME)
list(APPEND GLOBAL_ALL_TARGETS ${TARGET_NAME})
endmacro()

macro(AddTarget TARGET_NAME)
list(APPEND GLOBAL_ALL_TARGETS ${TARGET_NAME})
set(GLOBAL_ALL_TARGETS ${GLOBAL_ALL_TARGETS} CACHE STRING INTERNAL FORCE)
endmacro()

macro(ConfigureAll)
foreach(target ${GLOBAL_ALL_TARGETS})
ConfigureTarget(${target})
endforeach()
endmacro()
