if (NOT qtuser_FIND_COMPONENTS)
    set(qtuser_NOT_FOUND_MESSAGE "The qtuser package requires at least one component")
    set(qtuser_FOUND False)
    return()
endif()

set(qtuser_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/../qtuser/)
set(qtuser_LIB_DIRS ${CMAKE_BINARY_DIR}/../../lib/)
foreach(module ${qtuser_FIND_COMPONENTS})
	set(target qtuser::${module})
    if (NOT TARGET ${target})
		add_library(${target} SHARED IMPORTED)
		set_property(TARGET ${target} PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${qtuser_INCLUDE_DIRS}/${module})
		set_target_properties(${target} PROPERTIES IMPORTED_IMPLIB_RELEASE ${qtuser_LIB_DIRS}/Release/qtuser_${module}.lib)
		set_target_properties(${target} PROPERTIES IMPORTED_IMPLIB_DEBUG ${qtuser_LIB_DIRS}/Debug/qtuser_${module}.lib)
	endif()
endforeach()

set(qtuser_FOUND True)