macro(__enable_spdlog)
	if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/spdlog/CMakeLists.txt)
		add_subdirectory(spdlog)
		set(SPDLOG_FROM_SOURCE 1)
	else()
		__cc_find(Spdlog)
		set(SPDLOG_FROM_SOURCE 0)
	endif()
	
	if(TARGET spdlog)
		message(STATUS "__enable_spdlog success.")
		set(CC_GLOBAL_SPDLOG_ENABLED 1)
		if(SPDLOG_FROM_SOURCE)
			message(STATUS "from source.")
		else()
			message(STATUS "from binary.")
		endif()
	else()
		message(STATUS "__enable_spdlog failed.")
		set(CC_GLOBAL_SPDLOG_ENABLED 0)
	endif()
endmacro()