if(CONAN_CGAL_ROOT_RELEASE)
	set(CGAL_INCLUDE_DIRS ${CONAN_CGAL_ROOT_RELEASE}/include/ ${CONAN_CGAL_ROOT_RELEASE}/include/CGAL/Root/)
	message(STATUS "cgal CGAL_INCLUDE_DIRS : ${CGAL_INCLUDE_DIRS}")
endif()
