
if(CC_BC_WIN)
	__conan_import_one(ffmpeglib dll NAME avcodec LIB avcodec DLL avcodec-58)
	__conan_import_one(ffmpeglib dll NAME avdevice LIB avdevice DLL avdevice-58)
	__conan_import_one(ffmpeglib dll NAME avfilter LIB avfilter DLL avfilter-7)
	__conan_import_one(ffmpeglib dll NAME avformat LIB avformat DLL avformat-58)
	__conan_import_one(ffmpeglib dll NAME avutil LIB avutil DLL avutil-56)
	__conan_import_one(ffmpeglib dll NAME postproc LIB postproc DLL postproc-55)
	__conan_import_one(ffmpeglib dll NAME swresample LIB swresample DLL swresample-3)
	__conan_import_one(ffmpeglib dll NAME swscale LIB swscale DLL swscale-5)
elseif(CC_BC_LINUX)
	__conan_import(ffmpeglib dll COMPONENT avcodec avdevice avfilter avformat avutil swresample swscale)
elseif(CC_BC_MAC)
	__conan_import_one(ffmpeglib dll NAME avcodec DLL avcodec.58)
	__conan_import_one(ffmpeglib dll NAME avdevice DLL avdevice.58)
	__conan_import_one(ffmpeglib dll NAME avfilter DLL avfilter.7)
	__conan_import_one(ffmpeglib dll NAME avformat DLL avformat.58)
	__conan_import_one(ffmpeglib dll NAME avutil  DLL avutil.56)
	__conan_import_one(ffmpeglib dll NAME swresample DLL swresample.3)
	__conan_import_one(ffmpeglib dll NAME swscale  DLL swscale.5)
else()
	__conan_import(ffmpeglib dll COMPONENT avcodec avdevice avfilter avformat avutil postproc swresample swscale)
endif()